name: "Feature request"
description: "Suggest an idea for this project"
title: "[Feature] "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: "## Feature description\nA clear and concise description of what you want to happen."
  - type: textarea
    id: solution
    attributes:
      label: "Proposed solution"
      description: "Describe the solution you'd like."
      placeholder: "I would like ..."
    validations:
      required: true
