name: 🧪 Backend Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    env:
      MONGO_URI: mongodb://localhost:27017/merkato_test_ci
      JWT_SECRET: test_secret_key_ci
      STRIPE_SECRET_KEY: sk_test_placeholder
      STRIPE_PUBLISHABLE_KEY: pk_test_placeholder
      STRIPE_WEBHOOK_SECRET: whsec_test_placeholder
      CLIENT_URL: http://localhost:3000
      EMAIL_USER: test@example.com
      EMAIL_PASS: testpassword

    services:
      mongo:
        image: mongo:5
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run backend tests
        run: npm run test:backend
