// Centralized route constants and helpers
// Keep paths aligned with App.js and E2E specs

export const ROUTES = {
  home: '/',
  shop: '/shop',
  customers: '/customers',
  vendors: '/vendors',
  favorites: '/favorites',
  about: '/about',
  terms: '/terms',
  privacy: '/privacy',
  contact: '/contact',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  upload: '/upload',
  cart: '/cart',
  checkout: '/checkout',
  checkoutSuccess: '/checkout-success',
  orderConfirmation: '/order-confirmation',
  support: '/support',
  codex: '/codex',
  tasks: '/tasks',
  account: '/account',
  accountDashboard: '/account/dashboard',
  accountOrders: '/account/orders',
  accountGuide: '/account/guide',
  accountInbox: '/account/inbox',
  accountChat: '/account/chat/:userId',
  accountAddresses: '/account/addresses',
  accountWallet: '/account/wallet',
  accountRewards: '/account/rewards',
  accountNotifications: '/account/notifications',
  vendor: '/vendor',
  vendorDashboard: '/vendor/dashboard',
  vendorAccount: '/vendor/account',
  vendorOnboarding: '/vendor/onboarding',
  vendorOrders: '/vendor/orders',
  vendorProducts: '/vendor/products',
  vendorUpload: '/vendor/upload',
  vendorProductUpload: '/vendor/products/upload',
  vendorGuide: '/vendor/guide',
  vendorAnalytics: '/vendor/analytics',
  vendorInvoices: '/vendor/invoices',
  vendorMarketing: '/vendor/marketing',
  vendorChat: '/vendor/chat/:userId',
  vendorInbox: '/vendor/inbox',
  vendorQuestions: '/vendor/questions',
  admin: '/admin',
  adminDashboard: '/admin/dashboard',
  adminPromoCodes: '/admin/promo-codes',
  adminPromoManager: '/admin/promo-manager',
  adminVendors: '/admin/vendors',
  adminOrders: '/admin/orders',
  adminExpenses: '/admin/expenses',
  adminFeedback: '/admin/feedback',
  adminSupport: '/admin/support',
  adminAnalytics: '/admin/analytics',
  adminFlags: '/admin/flags',
  adminDiscount: '/admin/discount',
  adminReviewModeration: '/admin/review-moderation',
  adminDeliveryOptions: '/admin/delivery-options',
  adminInvoicesReport: '/admin/invoices/report',
  adminInvoices: '/admin/invoices',
};

export const buildRoute = {
  productDetail: (id) => `/product/${id}`,
  vendorStore: (id) => `/vendor/${id}`,
  accountChat: (userId) => `/account/chat/${userId}`,
  vendorChat: (userId) => `/vendor/chat/${userId}`,
};

export default ROUTES;
