name: Accessibility Check
on:
  pull_request:
    branches: [ main ]
jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pa11y
        run: npm install -g pa11y
      - name: Run pa11y (example on localhost)
        run: |
          pa11y http://localhost:3000 || echo "Accessibility issues found or pa11y not configured"
        continue-on-error: true
