# Auto-merge trusted bot PRs (Prettier, ESLint, Dependabot, npm audit)
# Uses peter-evans/enable-pull-request-automerge
name: "Auto-Merge Bot PRs"
on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]
jobs:
  automerge:
    if: |
      github.actor == 'dependabot[bot]' ||
      github.actor == 'github-actions[bot]' ||
      github.actor == 'renovate[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge for trusted bot PRs
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          pull-request-number: ${{ github.event.pull_request.number }}
