name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6
        ports: ["27017:27017"]
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")' || exit 1" 
          --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install backend deps
        run: npm ci
        working-directory: backend
      - name: Run backend tests
        env:
          MONGO_URI: mongodb://127.0.0.1:27017/merkato_test
          NODE_ENV: test
        run: npm test -- --runInBand
        working-directory: backend

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install frontend deps
        run: npm ci
        working-directory: frontend
      - name: Run frontend tests
        env:
          CI: true
        run: npm test -- --watchAll=false
        working-directory: frontend

