# ESLint auto-fix workflow: fixes lint errors and creates a PR with fixes
name: "ESLint Auto-Fix"
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          cd backend && npm ci
          cd ../frontend && npm ci
      - name: Run ESLint auto-fix (backend)
        run: |
          cd backend
          npx eslint . --fix || echo "No ESLint or nothing to fix in backend"
      - name: Run ESLint auto-fix (frontend)
        run: |
          cd ../frontend
          npx eslint . --fix || echo "No ESLint or nothing to fix in frontend"
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "chore: auto-fix lint errors with ESLint"
          git push || echo "No changes to commit"
