name: Frontend Baseline Verify

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  verify-frontend-baseline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Record baseline (if none) and verify
        working-directory: frontend
        env:
          CI: 'true'
        run: |
          if [ ! -f tests/utils/baseline-passing.json ]; then npm run test:baseline:record; fi
          npm run test:baseline:verify
