# npm audit auto-fix workflow: attempts to fix vulnerabilities and creates a PR with fixes
name: "npm Audit Auto-Fix"
on:
  schedule:
    - cron: '0 2 * * 0' # Weekly on Sunday
  workflow_dispatch:
jobs:
  audit-fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Run npm audit fix (backend)
        run: |
          cd backend
          npm ci
          npm audit fix || echo "No fixable vulnerabilities in backend"
      - name: Run npm audit fix (frontend)
        run: |
          cd ../frontend
          npm ci
          npm audit fix || echo "No fixable vulnerabilities in frontend"
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "chore: auto-fix npm audit vulnerabilities"
          git push || echo "No changes to commit"
