# Configuration for stale PR/issue management
# See: https://github.com/actions/stale
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue is stale because it has been open 30 days with no activity."
          stale-pr-message: "This PR is stale because it has been open 30 days with no activity."
          days-before-stale: 30
          days-before-close: 7
